Version: "3.8"
services:
  ldap:
    image: balenabalena/ldap21:grups
    container_name: ldap.edt.org
    hostname: ldap.edt.org
    ports: 
      - "389:389"
      - "636:636"
    networks:
     - 2hisix
    restart: always
  samba:
    image: balenabalena/samba21:stand-alone
    container_name: smb.edt.org
    hostname: smb.edt.org
    ports:
      - "445:445"
      - "139:139"
    networks:
     - 2hisix
    restart: always

